### ISSUE TITLE
Основной сайт недоступен из-за CF

### ISSUE THREAD

**Issue by Feodor0090** [Feodor0090/njtai#62]
Это полностью исключает прямой доступ и усложняет проксирование до уровня, что нам лень думать как его настраивать.

**Comment by R0ci0-V3rd3al** [comment]
это тоже всплывет снова? Многие веб-сайты сегодня активируют cloudflare, я не знаю, является ли это хаосом, который остановил многие экземпляры nhentai.

**Comment by shinovon** [comment]
![Screenshot_20240624-104344_Telegram](https://github.com/Feodor0090/njtai/assets/43963888/4ffac0f2-b47d-454d-a4c3-04ec1753a502)

**Comment by shinovon** [comment]
разрешилось само собой, кф убрали
